### ISSUE TITLE
The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by ssreelekhya** [KyberNetwork/fpr-sdk.js#31]
I bumped into error, when trying to call addToken() method of the Reserve(wrapper)
const rcontracts = new FPR.Reserve(provider, addresses)
 rcontracts.addToken(account, KNCTokenAddress, tokenControlInfo).then(
        result => {console.log(result)}
    )

**Comment by mingyeow** [comment]
I am pretty sure it is because this transaction was not signed. More generally, we need a way for user to store their private key in the reserve class and sign it before sending.

https://ethereum.stackexchange.com/questions/78496/the-method-eth-sendtransaction-does-not-exist-is-not-available-when-using-ropst?rq=1

```
  async addToken (account, token, tokenControlInfo, gasPrice) {
    validateAddress(token)
    await assertAdmin(this, account.address)
    let tx = this.contract.methods.addToken(token)
    await tx.send({
      from: account.address,
      gas: await tx.estimateGas({ from: account.address }),
      gasPrice: gasPrice
    })
```

**Comment by mingyeow** [comment]
More generally, we need a way for user to store their private key in the reserve class instance and sign transactions before sending.

**Comment by mingyeow** [comment]
fixed in [commit](https://github.com/KyberNetwork/fpr-sdk.js/pull/30/commits/2486ae3c5748733d993c2ca28d8af515734151f8)
